name: HeroesSkills
version: '${version}'
main: net.brian.heroesskills.HeroesSkills
api-version: 1.18
depend: [ PlayerDataSync,MMOItems,MythicLib,MythicMobs,PlaceholderAPI ]
softdepend:
  - HeroesDungeon
  - WorldGuard
commands:
  HeroesSkill:
    aliases: [hs]
